export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY'
export const CREATE_CATEGORY = 'CREATE_CATEGORY'
export const GET_ONE_CATEGORY = 'GET_ONE_CATEGORY'
export const GET_ERROR = 'GET_ERROR'

export const GET_ALL_VENDORS = 'GET_ALL_VENDORS'
export const CREATE_VENDOR = 'CREATE_VENDOR'

export const CREATE_SUBCATEGORY = 'CREATE_SUBCATEGORY'

export const GET_SUBCATEGORY = 'GET_SUBCATEGORY'


export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS'
export const GET_PRODUCTS_LIKE = 'GET_PRODUCTS_LIKE'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
